import type { ProfilePreset, RuleIconGroup } from "./types";

export const presetConnectionOptions: ProfilePreset["components"] = [
  { id: "transport-reality", transport: "xhttp", label: "VLESS · XHTTP" },
  { id: "transport-reality", transport: "raw", label: "VLESS · RAW" },
  { id: "transport-reality", transport: "grpc", label: "VLESS · gRPC" },
  { id: "transport-reality", tls: true, transport: "xhttp", label: "VLESS TLS · XHTTP" },
  { id: "transport-reality", tls: true, transport: "websocket", label: "VLESS TLS · WS" },
  { id: "transport-reality", tls: true, transport: "httpupgrade", label: "VLESS TLS · HTTPUpgrade" },
  { id: "transport-reality", tls: true, transport: "grpc", label: "VLESS TLS · gRPC" },
  { id: "transport-reality", cdn: true, transport: "xhttp", label: "VLESS CDN · XHTTP" },
  { id: "transport-reality", cdn: true, transport: "websocket", label: "VLESS CDN · WS" },
  { id: "transport-reality", cdn: true, transport: "httpupgrade", label: "VLESS CDN · HTTPUpgrade" },
  { id: "transport-reality", cdn: true, transport: "grpc", label: "VLESS CDN · gRPC" },
  { id: "transport-awg", label: "AWG" }, { id: "transport-wg", label: "WG" }, { id: "transport-shadowsocks", label: "SS" },
  { id: "transport-hysteria2", label: "Hysteria2" }, { id: "transport-tuic", label: "TUIC v5" },
];

export const presetOptionGroups = [
  { id: "direct", title: "VLESS REALITY", note: "Прямое подключение", options: presetConnectionOptions.filter((item) => item.id === "transport-reality" && !item.cdn && !item.tls) },
  { id: "tls", title: "VLESS TLS", note: "Прямой TLS-домен", options: presetConnectionOptions.filter((item) => item.id === "transport-reality" && item.tls) },
  { id: "cdn", title: "VLESS через CDN", note: "TLS завершается на CDN", options: presetConnectionOptions.filter((item) => item.id === "transport-reality" && item.cdn) },
  { id: "tunnels", title: "Туннели и QUIC", note: "Независимые каналы", options: presetConnectionOptions.filter((item) => item.id !== "transport-reality") },
];

export const channelShort: Record<string, string> = {
  "transport-awg": "AW",
  "transport-wg": "WG",
  "transport-reality": "VL",
  "transport-shadowsocks": "SS",
  "transport-hysteria2": "HY2",
  "transport-tuic": "TU",
};

export const devicePlatform: Record<string, { code: string; label: string }> = {
  ios: { code: "iOS", label: "iOS" }, android: { code: "AND", label: "Android" },
  macos: { code: "MAC", label: "macOS" }, windows: { code: "WIN", label: "Windows" },
  linux: { code: "LNX", label: "Linux" }, unknown: { code: "HW", label: "Неизвестная ОС" },
};

export const dnsProviderMeta: Record<string, { code: string; note: string }> = {
  "https://cloudflare-dns.com/dns-query": { code: "CF", note: "Быстрый DoH без фильтрации" },
  "https://dns.google/dns-query": { code: "G", note: "Публичный DoH Google" },
  "https://dns.quad9.net/dns-query": { code: "Q9", note: "Блокировка вредоносных доменов" },
  "https://dns.adguard-dns.com/dns-query": { code: "AG", note: "Реклама и трекеры" },
  "208.67.222.222": { code: "OD", note: "Базовая защита OpenDNS" },
  "185.228.168.9": { code: "CB", note: "Фильтрация опасных ресурсов" },
  "https://common.dot.dns.yandex.net/dns-query": { code: "YA", note: "Яндекс DNS без фильтрации" },
  "77.88.8.88": { code: "YA", note: "Безопасный режим Яндекс" },
  "77.88.8.7": { code: "FAM", note: "Семейная фильтрация" },
  "193.58.251.251": { code: "SKY", note: "Фильтрация SkyDNS" },
  "195.208.4.1": { code: "NS", note: "Российский резолвер НСДИ" },
  "195.46.39.39": { code: "SAFE", note: "Категорийная фильтрация" },
};

export const moduleCapabilities: Record<string, string[]> = {
  "transport-reality": ["REALITY", "TLS", "CDN", "XHTTP", "RAW", "gRPC", "WebSocket"],
  "transport-awg": ["AmneziaWG", "UDP"],
  "transport-wg": ["WireGuard", "UDP"],
  "transport-shadowsocks": ["Shadowsocks", "TCP", "UDP"],
  "transport-hysteria2": ["Hysteria2", "QUIC", "UDP", "Salamander"],
  "transport-tuic": ["TUIC v5", "QUIC", "UDP"],
};

export const directGameCatalog = [
  { id: "cs2", code: "CS2", name: "Counter-Strike 2" },
  { id: "dota2", code: "DOTA", name: "Dota 2" },
  { id: "valorant", code: "VAL", name: "Valorant" },
  { id: "fortnite", code: "FN", name: "Fortnite" },
  { id: "pubg", code: "PUBG", name: "PUBG" },
  { id: "warzone", code: "COD", name: "Call of Duty / Warzone" },
  { id: "gta5", code: "GTA", name: "GTA V" },
  { id: "roblox", code: "RBX", name: "Roblox" },
  { id: "wot", code: "WOT", name: "World of Tanks" },
  { id: "tarkov", code: "EFT", name: "Escape from Tarkov" },
  { id: "apex", code: "APEX", name: "Apex Legends" },
  { id: "rainbow6", code: "R6", name: "Rainbow Six Siege" },
  { id: "overwatch2", code: "OW2", name: "Overwatch 2" },
  { id: "rocketleague", code: "RL", name: "Rocket League" },
  { id: "lol", code: "LOL", name: "League of Legends" },
  { id: "destiny2", code: "D2", name: "Destiny 2" },
  { id: "helldivers2", code: "HD2", name: "Helldivers 2" },
  { id: "rust", code: "RUST", name: "Rust" },
  { id: "warthunder", code: "WT", name: "War Thunder" },
  { id: "dbd", code: "DBD", name: "Dead by Daylight" },
  { id: "thefinals", code: "TF", name: "The Finals" },
  { id: "battlefield2042", code: "BF", name: "Battlefield 2042" },
  { id: "brawlstars", code: "BS", name: "Brawl Stars" },
  { id: "freefire", code: "FF", name: "Free Fire" },
  { id: "mobilelegends", code: "ML", name: "Mobile Legends" },
  { id: "diablo4", code: "D4", name: "Diablo IV" },
  { id: "arenabreakoutinfinite", code: "ABI", name: "Arena Breakout: Infinite" },
  { id: "marathon", code: "MAR", name: "Marathon" },
  { id: "repo", code: "REPO", name: "R.E.P.O." },
  { id: "mistfallhunter", code: "MFH", name: "Mistfall Hunter" },
  { id: "residentevilrequiem", code: "RE9", name: "Resident Evil Requiem" },
  { id: "stardewvalley", code: "SDV", name: "Stardew Valley" },
  { id: "mecchachameleon", code: "MC", name: "MECCHA CHAMELEON" },
  { id: "minecraft", code: "MC", name: "Minecraft" },
  { id: "warface", code: "WF", name: "Warface" },
  { id: "enlisted", code: "ENL", name: "Enlisted" },
  { id: "worldofwarships", code: "WOWS", name: "World of Warships" },
  { id: "pathofexile2", code: "POE", name: "Path of Exile 2" },
  { id: "warframe", code: "WF", name: "Warframe" },
  { id: "genshin", code: "GI", name: "Genshin Impact" },
  { id: "honkai", code: "HSR", name: "Honkai: Star Rail" },
  { id: "deltaforce", code: "DF", name: "Delta Force" },
  { id: "marvelrivals", code: "MR", name: "Marvel Rivals" },
  { id: "deadlock", code: "DL", name: "Deadlock" },
  { id: "atomicheart", code: "AH", name: "Atomic Heart" },
  { id: "stalcraft", code: "SCX", name: "STALCRAFT: X" },
  { id: "crossout", code: "CROSS", name: "Crossout" },
  { id: "lostark", code: "LA", name: "Lost Ark" },
  { id: "blackdesert", code: "BDO", name: "Black Desert" },
  { id: "albion", code: "AO", name: "Albion Online" },
  { id: "eveonline", code: "EVE", name: "EVE Online" },
  { id: "dayz", code: "DAYZ", name: "DayZ" },
  { id: "arma3", code: "ARMA", name: "Arma 3" },
  { id: "huntshowdown", code: "HUNT", name: "Hunt: Showdown 1896" },
  { id: "remnant2", code: "R2", name: "Remnant II" },
  { id: "palworld", code: "PAL", name: "Palworld" },
  { id: "oncehuman", code: "OH", name: "Once Human" },
  { id: "throneandliberty", code: "TL", name: "Throne and Liberty" },
  { id: "escapefromduckov", code: "EFD", name: "Escape from Duckov" },
];

export const tunnelGameCatalog = [
  { id: "brawlstars", code: "BS", name: "Brawl Stars", family: "Supercell" },
  { id: "clashofclans", code: "COC", name: "Clash of Clans", family: "Supercell" },
  { id: "clashroyale", code: "CR", name: "Clash Royale", family: "Supercell" },
  { id: "boombeach", code: "BB", name: "Boom Beach", family: "Supercell" },
  { id: "hayday", code: "HD", name: "Hay Day", family: "Supercell" },
  { id: "apex", code: "APEX", name: "Apex Legends", family: "EA" },
  { id: "battlefield2042", code: "BF42", name: "Battlefield 2042", family: "EA" },
  { id: "battlefield6", code: "BF6", name: "Battlefield 6", family: "EA" },
  { id: "eafc25", code: "FC25", name: "EA Sports FC 25", family: "EA" },
  { id: "eafc26", code: "FC26", name: "EA Sports FC 26", family: "EA" },
  { id: "f125", code: "F1", name: "F1 25", family: "EA" },
  { id: "nfsunbound", code: "NFS", name: "Need for Speed Unbound", family: "EA" },
  { id: "battlefront2", code: "SW", name: "Star Wars Battlefront II", family: "EA" },
];

export const gameRoutingCatalog = [...new Map([
  ...directGameCatalog.map((game) => ({ ...game, family: "Обычный маршрут" })),
  ...tunnelGameCatalog,
].map((game) => [game.id, game])).values()];

export const defaultTunnelGameIds = new Set(tunnelGameCatalog.map((game) => game.id));

export const defaultDirectGameIds = new Set(directGameCatalog.map((game) => game.id).filter((id) => !defaultTunnelGameIds.has(id)));

export const udpExclusionCatalog = [
  { id: "dns", code: "DNS", name: "Защищённый DNS" },
  { id: "telegram", code: "TG", name: "Telegram" },
  { id: "discord", code: "DS", name: "Discord" },
  { id: "whatsapp", code: "WA", name: "WhatsApp" },
  { id: "signal", code: "SG", name: "Signal" },
  { id: "zoom", code: "ZM", name: "Zoom" },
  { id: "meet", code: "GM", name: "Google Meet" },
  { id: "teams", code: "MS", name: "Teams / Skype" },
  { id: "apple", code: "AP", name: "FaceTime / iMessage" },
  { id: "steam", code: "ST", name: "Steam" },
  { id: "ea", code: "EA", name: "EA" },
  { id: "supercell", code: "SC", name: "Supercell" },
  { id: "riot", code: "RI", name: "Riot Games" },
  { id: "epic", code: "EP", name: "Epic / Fortnite" },
  { id: "xbox", code: "XB", name: "Xbox Live" },
  { id: "playstation", code: "PS", name: "PlayStation Network" },
  { id: "nintendo", code: "NS", name: "Nintendo" },
  { id: "battlenet", code: "BN", name: "Battle.net" },
];

export const p2pClientCatalog = [
  { id: "qbittorrent", code: "QBIT", name: "qBittorrent" },
  { id: "transmission", code: "TR", name: "Transmission" },
  { id: "deluge", code: "DEL", name: "Deluge" },
  { id: "utorrent", code: "µT", name: "µTorrent" },
  { id: "bittorrent", code: "BT", name: "BitTorrent" },
  { id: "biglybt", code: "BIG", name: "BiglyBT" },
  { id: "tribler", code: "TRIB", name: "Tribler" },
  { id: "frostwire", code: "FW", name: "FrostWire" },
];

export const profileDirectRules = [
  { key: "block_ads", code: "AD", title: "Реклама", text: "Реклама и рекламные трекеры.", group: "Защита" },
  { key: "block_privacy", code: "PRIV", title: "Приватность", text: "Аналитика и профилирование.", group: "Защита" },
  { key: "direct_ru_sites", code: "RU", title: "Сайты РФ", text: "Домены и IP России.", group: "Напрямую" },
  { key: "direct_ru_banks", code: "BANK", title: "Банки", text: "Банки и платёжные сервисы.", group: "Напрямую" },
  { key: "direct_ru_marketplaces", code: "SHOP", title: "Магазины", text: "Магазины и маркетплейсы.", group: "Напрямую" },
  { key: "direct_downloads", code: "DL", title: "Загрузки", text: "Крупные файлы без VPN.", group: "Напрямую" },
  { key: "direct_local_network", code: "LAN", title: "Локальная сеть", text: "Домашние устройства напрямую.", group: "Сеть" },
  { key: "direct_games_enabled", code: "GAME", title: "Игры", text: "Выбранные игры без VPN.", group: "Сеть" },
  { key: "direct_games_udp_enabled", code: "UDP", title: "UDP", text: "Весь UDP без VPN.", group: "Сеть" },
  { key: "direct_p2p_enabled", code: "P2P", title: "P2P и торренты", text: "Выбранные клиенты напрямую.", group: "Сеть" },
];

export const ruleIconGroups: Record<string, RuleIconGroup[]> = {
  block_ads: [
    { id: "base", code: "AD", name: "Базовый список рекламы", tokens: ["category-ads-all"] },
    { id: "google", code: "G ADS", name: "Google Ads", tokens: ["doubleclick", "googlesyndication", "googleadservices", "googletagservices"] },
    { id: "yandex", code: "YA AD", name: "Яндекс Реклама", tokens: ["yandexadexchange", "an.yandex.ru", "adfox"] },
    { id: "vk_ads", code: "VK AD", name: "VK / myTarget", tokens: ["mytarget"] },
    { id: "native", code: "NATIVE", name: "Taboola и Outbrain", tokens: ["taboola", "outbrain"] },
    { id: "criteo", code: "CRITEO", name: "Criteo", tokens: ["criteo"] },
    { id: "amazon", code: "AMZ", name: "Amazon Ads", tokens: ["amazon-adsystem"] },
    { id: "global_rtb", code: "RTB", name: "Международные RTB-сети", tokens: ["adnxs", "adsrvr", "adform", "adroll", "openx", "pubmatic", "rubiconproject", "casalemedia", "serving-sys", "smartadserver", "smaato", "yieldmo", "lijit", "media.net", "advertising.com"] },
    { id: "ru_rtb", code: "RU RTB", name: "Российские RTB-сети", tokens: ["between.digital", "adriver", "soloway", "buzzoola", "hybrid.ai", "otm-r", "videonow"] },
    { id: "mobile", code: "APP", name: "Реклама в приложениях", tokens: ["applovin", "applvn", "vungle", "ironsrc", "chartboost", "inmobi", "adcolony", "startappservice", "mintegral", "unityads"] },
    { id: "video", code: "VIDEO", name: "Реклама в видео", tokens: ["springserve", "spotx", "freewheel", "fwmrm", "innovid", "tremorhub", "unrulymedia", "cedato", "connatix", "aniview", "teads", "smartclip", "lkqd"] },
    { id: "metrics", code: "TRACK", name: "Рекламные измерения", tokens: ["scorecardresearch", "moatads", "adsafeprotected"] },
  ],
  block_privacy: [
    { id: "google", code: "GA", name: "Google Analytics", tokens: ["google-analytics"] },
    { id: "yandex", code: "YM", name: "Яндекс Метрика", tokens: ["mc.yandex"] },
    { id: "clarity", code: "CLARITY", name: "Microsoft Clarity", tokens: ["clarity.ms"] },
    { id: "hotjar", code: "HOTJAR", name: "Hotjar", tokens: ["hotjar"] },
    { id: "fullstory", code: "FS", name: "FullStory", tokens: ["fullstory"] },
    { id: "mixpanel", code: "MIX", name: "Mixpanel", tokens: ["mixpanel"] },
    { id: "amplitude", code: "AMP", name: "Amplitude", tokens: ["amplitude"] },
    { id: "heap", code: "HEAP", name: "Heap", tokens: ["heap.io"] },
    { id: "segment", code: "SEG", name: "Segment", tokens: ["segment.com", "segment.io"] },
    { id: "firebase", code: "FBA", name: "Firebase Analytics", tokens: ["app-measurement"] },
    { id: "appsflyer", code: "AF", name: "AppsFlyer", tokens: ["appsflyer"] },
    { id: "adjust", code: "ADJ", name: "Adjust", tokens: ["adjust.com", "adjust.net.in"] },
    { id: "branch", code: "BR", name: "Branch", tokens: ["branch.io"] },
    { id: "singular", code: "SG", name: "Singular", tokens: ["singular.net"] },
    { id: "kochava", code: "KO", name: "Kochava", tokens: ["kochava"] },
    { id: "tiktok", code: "TT", name: "TikTok Analytics", tokens: ["analytics.tiktok"] },
    { id: "social", code: "SOC", name: "Другие соцсети", tokens: ["analytics.twitter", "snap.licdn", "tr.snapchat"] },
    { id: "scorecard", code: "SCR", name: "Comscore", tokens: ["scorecardresearch"] },
    { id: "windows", code: "WIN", name: "Телеметрия Windows", tokens: ["microsoft.com"] },
    { id: "nvidia", code: "NV", name: "Телеметрия NVIDIA", tokens: ["gfe.nvidia"] },
    { id: "amd", code: "AMD", name: "Телеметрия AMD", tokens: ["metrics.amd"] },
    { id: "mozilla", code: "FF", name: "Телеметрия Firefox", tokens: ["telemetry.mozilla"] },
    { id: "jetbrains", code: "JB", name: "Статистика JetBrains", tokens: ["data.services.jetbrains"] },
    { id: "ubuntu", code: "UBU", name: "Отчёты Ubuntu", tokens: ["errors.ubuntu"] },
    { id: "unity", code: "UNITY", name: "Unity Analytics", tokens: ["cloud.unity3d"] },
  ],
  direct_ru_sites: [
    { id: "zones", code: "RU", name: "Домены и IP России", tokens: ["DOMAIN-SUFFIX,ru,", "xn--p1ai", "DOMAIN-SUFFIX,su,", "GEOIP,RU"] },
    { id: "yandex", code: "YA", name: "Яндекс", tokens: ["yandex", "yastatic"] },
    { id: "vk", code: "VK", name: "ВКонтакте", tokens: ["vk.ru", "vk.com", "userapi", "vkuseraudio"] },
    { id: "mail", code: "MAIL", name: "Mail.ru", tokens: ["mail.com"] },
    { id: "ok", code: "OK", name: "Одноклассники", tokens: ["mycdn", "ok.ru", "odnoklassniki"] },
    { id: "dzen", code: "DZEN", name: "Дзен", tokens: ["dzen.ru"] },
    { id: "rutube", code: "RUTUBE", name: "Rutube", tokens: ["rutube"] },
    { id: "smotrim", code: "TV", name: "Смотрим", tokens: ["smotrim"] },
    { id: "kinopoisk", code: "KP", name: "Кинопоиск", tokens: ["kinopoisk"] },
    { id: "twogis", code: "2GIS", name: "2ГИС", tokens: ["2gis"] },
    { id: "gosuslugi", code: "GOS", name: "Госуслуги", tokens: ["gosuslugi"] },
    { id: "mos", code: "MOS", name: "Мос.ру", tokens: ["mos.ru"] },
    { id: "nalog", code: "FNS", name: "ФНС", tokens: ["nalog.gov.ru"] },
    { id: "kaspersky", code: "KAV", name: "Лаборатория Касперского", tokens: ["kaspersky"] },
  ],
  direct_ru_banks: [
    { id: "sber", code: "SBER", name: "Сбер", tokens: ["sber"] },
    { id: "tbank", code: "TB", name: "Т-Банк", tokens: ["tinkoff", "tbank"] },
    { id: "alfa", code: "ALFA", name: "Альфа-Банк", tokens: ["alfabank", "alfa-bank"] },
    { id: "vtb", code: "VTB", name: "ВТБ", tokens: ["vtb"] },
    { id: "gazprom", code: "GPB", name: "Газпромбанк", tokens: ["gazprombank"] },
    { id: "raiffeisen", code: "RAIF", name: "Райффайзен", tokens: ["raiffeisen"] },
    { id: "psb", code: "PSB", name: "ПСБ", tokens: ["psbank"] },
    { id: "sovcom", code: "SOV", name: "Совкомбанк", tokens: ["sovcombank"] },
    { id: "other_major", code: "BANK", name: "Другие крупные банки", tokens: ["open.ru", "rshb", "pochtabank", "mkb.ru", "uralsib"] },
    { id: "payments", code: "PAY", name: "Платежи и регуляторы", tokens: ["nspk", "mironline", "unistream", "coronapay", "cbr.ru", "fincult", "banki.ru", "finuslugi"] },
    { id: "regional", code: "BANK+", name: "Региональные банки", tokens: [] },
  ],
  direct_ru_marketplaces: [
    { id: "ozon", code: "OZON", name: "Ozon", tokens: ["ozon"] },
    { id: "wildberries", code: "WB", name: "Wildberries", tokens: ["wildberries", "wbbasket", "wb.ru"] },
    { id: "yandex_market", code: "YA M", name: "Яндекс Маркет", tokens: ["market.yandex", "beru"] },
    { id: "megamarket", code: "MEGA", name: "Мегамаркет", tokens: ["megamarket", "goods.ru"] },
    { id: "aliexpress", code: "ALI", name: "AliExpress Россия", tokens: ["aliexpress"] },
    { id: "regional_market", code: "MARKET", name: "Другие маркетплейсы", tokens: ["kazanexpress", "magnitmarket"] },
    { id: "classifieds", code: "AVITO", name: "Объявления", tokens: ["avito"] },
    { id: "fashion", code: "FASHION", name: "Lamoda и Золотое Яблоко", tokens: ["lamoda", "goldapple"] },
    { id: "kids_sport", code: "LIFE", name: "Детский мир и Спортмастер", tokens: ["detmir", "sportmaster"] },
    { id: "home", code: "HOME", name: "Дом и ремонт", tokens: ["leroymerlin", "lemanapro", "vseinstrumenti", "petrovich", "hoff"] },
    { id: "electronics", code: "TECH", name: "Электроника", tokens: ["citilink", "dns-shop", "mvideo", "eldorado", "onlinetrade"] },
    { id: "delivery", code: "FOOD", name: "Продукты и доставка", tokens: ["samokat", "kuper", "vprok", "lenta.com"] },
  ],
  direct_downloads: [
    { id: "windows", code: "WIN", name: "Windows Update", tokens: ["windowsupdate", "update.microsoft", "delivery.mp.microsoft"] },
    { id: "microsoft", code: "MS", name: "Загрузки Microsoft", tokens: ["download.microsoft"] },
    { id: "apple", code: "APPLE", name: "Обновления Apple", tokens: ["swcdn.apple", "swdownload.apple", "swdist.apple", "appldnld.apple", "mesu.apple"] },
    { id: "nvidia", code: "NV", name: "Драйверы NVIDIA", tokens: ["nvidia"] },
    { id: "amd", code: "AMD", name: "Драйверы AMD", tokens: ["drivers.amd"] },
    { id: "steam", code: "STEAM", name: "Загрузки Steam", tokens: ["steamcontent", "steamserver", "steamstatic", "steamcdn"] },
    { id: "epic", code: "EPIC", name: "Загрузки Epic Games", tokens: ["epicgames"] },
    { id: "ea", code: "EA", name: "Загрузки EA", tokens: ["origin-a", "eaassets"] },
    { id: "blizzard", code: "BN", name: "Загрузки Battle.net", tokens: ["level3.blizzard", "blzddist"] },
    { id: "xbox", code: "XBOX", name: "Загрузки Xbox", tokens: ["xboxlive"] },
    { id: "playstation", code: "PS", name: "Загрузки PlayStation", tokens: ["playstation.net"] },
    { id: "nintendo", code: "NS", name: "Загрузки Nintendo", tokens: ["nintendo.net"] },
    { id: "linux", code: "LINUX", name: "Ubuntu, Debian и Kernel", tokens: ["ubuntu", "debian", "kernel.org"] },
    { id: "github", code: "GH", name: "Релизы GitHub", tokens: ["githubusercontent"] },
    { id: "docker", code: "DOCKER", name: "Образы Docker", tokens: ["docker"] },
    { id: "jetbrains", code: "JB", name: "JetBrains", tokens: ["jetbrains"] },
    { id: "nodejs", code: "NODE", name: "Node.js", tokens: ["nodejs.org"] },
  ],
  direct_local_network: [
    { id: "names", code: "LAN", name: "Локальные имена", tokens: ["localhost", "DOMAIN-SUFFIX,local", "DOMAIN-SUFFIX,lan", "home.arpa"] },
    { id: "private_v4", code: "IPv4", name: "Приватные IPv4", tokens: ["10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16"] },
    { id: "private_v6", code: "IPv6", name: "Локальные IPv6", tokens: ["::1/128", "fc00::/7", "fe80::/10"] },
    { id: "discovery", code: "CAST", name: "Обнаружение устройств", tokens: ["224.0.0.0/4", "ff00::/8"] },
  ],
};

export const profileStrategies = [
  { value: "", code: "AUTO", title: "Общие", text: "Наследовать стратегию маршрутизации." },
  { value: "fallback", code: "SAFE", title: "Резерв", text: "Переключаться при недоступности канала." },
  { value: "url-test", code: "FAST", title: "Автовыбор", text: "Автоматически выбирать самый быстрый канал." },
  { value: "select", code: "MAN", title: "Вручную", text: "Показывать Selector в Mihomo-клиенте." },
];
