"use client";

import { useState } from "react";
import type { Protocol } from "../../shared/types/control-plane";
import { ProtocolIcon } from "../../shared/components/protocol-icon";

type GuideProps = { installedProtocols: Protocol[] };
type GuideItem = { title: string; file: string; importText: string; steps: string[]; clients: Array<{ name: string; href: string; note: string }>; qr?: string };

const apps = {
  amnezia: { name: "Amnezia", href: "https://amnezia.org/downloads" },
  amneziaWg: { name: "AmneziaWG", href: "https://docs.amnezia.org/documentation/alternative-clients/" },
  wireguard: { name: "WireGuard", href: "https://www.wireguard.com/install/" },
  hiddify: { name: "Hiddify", href: "https://hiddify.com/" },
  outline: { name: "Outline Client", href: "https://getoutline.org/get-started/" },
  openvpn: { name: "OpenVPN Connect", href: "https://openvpn.net/client/" },
};

const guides: Record<Protocol, GuideItem> = {
  wg: { title: "WireGuard", file: "*.conf", importText: "Импортируйте файл WireGuard или отсканируйте QR-код.", steps: ["Установите WireGuard или AmneziaWG.", "Выберите добавление туннеля из файла или QR-кода.", "Импортируйте выданный файл и включите туннель."], clients: [{ ...apps.wireguard, note: "Официальный клиент для Windows, macOS, Linux, iOS и Android." }, { ...apps.amneziaWg, note: "Также принимает обычные WG-конфигурации." }], qr: "QR-код можно отсканировать прямо в приложении." },
  awg: { title: "AmneziaWG", file: "*.conf", importText: "Используйте клиент с поддержкой AmneziaWG: параметры маскировки уже находятся в файле.", steps: ["Установите AmneziaWG.", "Выберите импорт конфигурации из файла или QR-кода.", "Не изменяйте Jc, Jmin, Jmax, S1–S4, H1–H4 и I1–I5 вручную.", "Включите добавленный туннель."], clients: [{ ...apps.amneziaWg, note: "Официальное приложение AmneziaWG." }, { ...apps.amnezia, note: "Клиент Amnezia также поддерживает AmneziaWG." }], qr: "QR-код сканируйте в AmneziaWG, а не в обычном WireGuard." },
  shadowsocks: { title: "Shadowsocks", file: "*.txt · ss://", importText: "Файл содержит ссылку ss://. Надёжнее передавать её через кнопку копирования или импорт файла.", steps: ["Установите клиент Shadowsocks или Outline Client.", "Добавьте сервер через ссылку ss:// или импортируйте текстовый файл.", "Подтвердите системный VPN-запрос и включите прокси."], clients: [{ ...apps.outline, note: "Простой клиент для ключей доступа." }, { ...apps.hiddify, note: "Универсальный клиент с поддержкой Shadowsocks." }] },
  "vless-reality-xhttp": { title: "VLESS", file: "*.txt · VLESS-ссылка", importText: "Выберите профиль REALITY, TLS или CDN и импортируйте соответствующую VLESS-ссылку.", steps: ["Установите клиент с поддержкой VLESS/Xray.", "Скопируйте содержимое текстового файла или отсканируйте QR-код.", "Добавьте ссылку в клиент и включите профиль.", "Для CDN используйте профиль CDN, для REALITY — профиль REALITY."], clients: [{ ...apps.hiddify, note: "Поддерживает VLESS, Reality, XHTTP, WebSocket, gRPC и CDN." }, { name: "v2rayNG / V2Box / Streisand", href: "https://docs.amnezia.org/documentation/alternative-clients/", note: "Выберите приложение для своей ОС из списка XRay-клиентов." }], qr: "QR-код удобен для VLESS-ссылки; при ошибке импортируйте текстовый файл." },
  hysteria2: { title: "Hysteria2", file: "*.yaml", importText: "Импортируйте YAML-профиль в клиент с поддержкой Hysteria2 или перенесите параметры из файла.", steps: ["Установите Hiddify или другой клиент с поддержкой Hysteria2.", "Выберите импорт локального YAML-файла либо добавление профиля вручную.", "Проверьте server, auth, SNI, pinSHA256 и obfs, если они указаны.", "Сохраните профиль и включите подключение."], clients: [{ ...apps.hiddify, note: "Работает на iOS, Android, Windows, macOS и Linux." }] },
  tuic: { title: "TUIC v5", file: "*.json", importText: "JSON-файл содержит готовый профиль sing-box с TUIC v5.", steps: ["Установите клиент с поддержкой sing-box/TUIC.", "Импортируйте JSON-файл как конфигурацию или профиль sing-box.", "Убедитесь, что сертификат и server name импортированы вместе с профилем.", "Сохраните профиль и включите подключение."], clients: [{ ...apps.hiddify, note: "Поддерживает TUIC и конфигурации sing-box." }] },
  trojan: { title: "Trojan", file: "*.json", importText: "JSON-файл содержит готовый профиль sing-box с TLS и паролем Trojan.", steps: ["Установите клиент с поддержкой Trojan/sing-box.", "Импортируйте JSON-файл или добавьте профиль по его параметрам.", "Не меняйте server name и пароль из выданной конфигурации.", "Сохраните профиль и включите подключение."], clients: [{ ...apps.hiddify, note: "Поддерживает Trojan и TLS-профили." }] },
  openvpn: { title: "OpenVPN", file: "*.ovpn", importText: "Файл .ovpn уже содержит сертификат устройства и параметры tls-crypt.", steps: ["Установите OpenVPN Connect.", "Выберите импорт профиля из файла .ovpn.", "Разрешите создание VPN-подключения и включите профиль.", "Не редактируйте сертификаты и закрытый ключ внутри файла."], clients: [{ ...apps.openvpn, note: "Официальный клиент для Windows, macOS, Linux, iOS и Android." }] },
  ikev2: { title: "IKEv2", file: "*.txt", importText: "Текстовый файл содержит сервер, Remote ID, логин, пароль и CA-сертификат.", steps: ["Откройте настройки VPN устройства или Amnezia.", "Создайте профиль IKEv2: сервер и Remote ID возьмите из файла.", "Укажите логин и пароль EAP-MSCHAPv2.", "Установите CA-сертификат из файла как доверенный и включите VPN."], clients: [{ ...apps.amnezia, note: "Поддерживает IKEv2 и упрощает импорт параметров." }, { name: "Системный IKEv2", href: "https://docs.amnezia.org/documentation/alternative-clients/", note: "На iOS, macOS и Windows можно использовать встроенный VPN-клиент ОС." }] },
};

export function ConnectionGuide({ installedProtocols }: GuideProps) {
  const [openProtocol, setOpenProtocol] = useState<Protocol | null>(installedProtocols[0] || null);
  const ru = true;
  const visibleGuides = installedProtocols.map((protocol) => [protocol, guides[protocol]] as const).filter((entry): entry is readonly [Protocol, GuideItem] => Boolean(entry[1]));

  return <article className="connectionGuide">
    <header><div><p className="eyebrow">CONNECTION WORKFLOW</p><h2>Подключение по выбранному протоколу</h2><span>Выберите установленный протокол и используйте подходящее приложение для импорта файла или ссылки.</span></div></header>
    <div className="connectionGuideSteps"><section><span>01</span><div><strong>{ru ? "Создайте доступ" : "Create access"}</strong><p>{ru ? "Одно подключение предназначено для одного устройства. После создания скачайте файл или передайте QR-код владельцу." : "One connection is for one device. After creation, download the file or show the QR code to its owner."}</p></div></section><section><span>02</span><div><strong>{ru ? "Выберите протокол" : "Choose the protocol"}</strong><p>{ru ? "Способ импорта и приложение зависят от формата конфигурации. Ниже отображаются только установленные протоколы." : "The import method and app depend on the configuration format. Only installed protocols are shown below."}</p></div></section><section><span>03</span><div><strong>{ru ? "Проверьте подключение" : "Verify the connection"}</strong><p>{ru ? "После включения проверьте статус в приложении и появление активности в строке устройства этой панели." : "After connecting, verify the app status and activity in this panel's device row."}</p></div></section></div>
    <div className="connectionGuideProtocols"><label className="connectionGuideSelect"><span>Установленный протокол</span><select value={openProtocol || ""} onChange={(event) => setOpenProtocol(event.target.value as Protocol)}>{visibleGuides.map(([protocol, guide]) => <option key={protocol} value={protocol}>{guide.title} · {guide.file}</option>)}</select></label>{visibleGuides.map(([protocol, guide]) => { const open = openProtocol === protocol; return <section className={`connectionGuideProtocol protocol-${protocol}${open ? " is-open" : ""}`} key={protocol}><button type="button" className="connectionGuideProtocolHead" aria-expanded={open} onClick={() => setOpenProtocol(open ? null : protocol)}><span className="connectionGuideProtocolIcon"><ProtocolIcon protocol={protocol} /></span><span><strong>{guide.title}</strong><small>{guide.file}</small></span><i>{open ? "−" : "+"}</i></button>{open && <div className="connectionGuideProtocolBody"><p className="connectionGuideLead">{guide.importText}</p><div className="connectionGuideColumns"><div><h3>Шаги</h3><ol>{guide.steps.map((step) => <li key={step}>{step}</li>)}</ol>{guide.qr && <p className="connectionGuideHint">{guide.qr}</p>}</div><div><h3>Подходящие приложения</h3><ul className="connectionGuideApps">{guide.clients.map((client) => <li key={client.name}><a href={client.href} target="_blank" rel="noreferrer">{client.name}</a><small>{client.note}</small></li>)}</ul></div></div></div>}</section>; })}</div>
    <footer><span>{ru ? "Важно: конфигурации содержат секреты доступа." : "Important: configurations contain access secrets."}</span><span>{ru ? "Не отправляйте файлы и QR-коды в открытые чаты." : "Do not send files or QR codes in public chats."}</span></footer>
  </article>;
}
