"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DnsCheck, DnsSettings, DnsStatus } from "../../types/control-plane";

type Props = { dns: DnsStatus | null; dnsDraft: DnsSettings | null; dnsChecks: Record<string, DnsCheck>; checkingDns: boolean; busy: boolean; setDnsDraft: Dispatch<SetStateAction<DnsSettings | null>>; checkDnsProviders: (providerId?: string) => Promise<void> | void; saveDnsSettings: () => Promise<void> | void };
const scope = [["apply_system","VPS","Локальный resolver сервера"],["apply_wg","WG","Новые WireGuard-профили"],["apply_awg","AWG","Новые AmneziaWG-профили"],["apply_shadowsocks","SS","Рекомендация клиенту"],["apply_vrx","VRX","Серверный Xray"]] as const;

export function DnsView({ dns, dnsDraft, dnsChecks, checkingDns, busy, setDnsDraft, checkDnsProviders, saveDnsSettings }: Props) {
  const selected = dns?.providers.find((item) => item.id === dnsDraft?.selected_id);
  const selectedName = selected?.name || dnsDraft?.custom?.name || "DNS не выбран";
  const enabledScopes = scope.filter(([key]) => Boolean(dnsDraft?.[key])).length;
  const systemDnsAvailable = dns?.system_resolver?.available !== false;
  return <section className="dnsWorkspace dnsWorkspaceV2">
    <header className="dnsPageHead plainPageHead"><div><p className="eyebrow">NETWORK & DNS</p><h1>Сеть и DNS</h1><p>Настройка локального resolver VPS, DNS новых VPN-профилей и серверного VRX.</p></div><div className="dnsPageFacts"><span><small>ПРОФИЛЬ</small><strong>{selectedName}</strong></span><span><small>КОНТУРЫ</small><strong>{enabledScopes}/5</strong></span><span><small>VPS DNS</small><strong>{dns?.system_resolver?.managed ? "MANAGED" : "SYSTEM"}</strong></span></div></header>
    <div className="dnsWorkbench">
      <article className="dnsResolverBrowser"><div className="dnsResolverArt" aria-hidden="true" /><header><div><p className="eyebrow">RESOLVER CATALOG</p><h2>Доступные DNS</h2><span>Проверяйте ответ с этого VPS перед выбором.</span></div><button type="button" onClick={() => void checkDnsProviders()} disabled={checkingDns}>{checkingDns ? "Проверяем…" : "Проверить все"}</button></header><div className="dnsResolverRows">{(dns?.providers || []).map((provider) => { const check=dnsChecks[provider.id]; const active=dnsDraft?.selected_id===provider.id; return <button type="button" className={`dnsResolverCard ${active ? "selected" : ""}`} key={provider.id} onClick={() => setDnsDraft((value) => value ? {...value,selected_id:provider.id}:value)}><span className="dnsResolverCountry">{provider.country}</span><span className="dnsResolverName"><strong>{provider.name}</strong><small>{provider.filter}</small><code>{provider.addresses.join("  ")}</code></span><span className="dnsResolverProbe"><b className={check?.udp_ok ? "ok":""}>UDP {check?.udp_ms != null ? `${check.udp_ms} ms`:"—"}</b><b className={check?.doh_ok ? "ok":""}>DoH {check?.doh_ms != null ? `${check.doh_ms} ms`:provider.doh_url ? "—":"нет"}</b></span><em>{active ? "ВЫБРАН":"ВЫБРАТЬ"}</em></button>; })}</div></article>
      <aside className="dnsPolicyConsole"><header><p className="eyebrow">DNS POLICY</p><h2>Куда применять</h2><span>Изменения затронут только отмеченные контуры.</span></header><div className="dnsScopeList">{scope.map(([key,code,description]) => <label className={dnsDraft?.[key] ? "active":""} key={key}><input type="checkbox" disabled={key === "apply_system" && !systemDnsAvailable} checked={dnsDraft?.[key] ?? true} onChange={(event) => setDnsDraft((value) => value ? {...value,[key]:event.target.checked}:value)} /><b>{code}</b><span><strong>{key === "apply_system" ? "DNS самого VPS":description}</strong><small>{key === "apply_system" ? `${dns?.system_resolver?.mode || "resolver"}  ${(dns?.system_resolver?.servers || []).join("  ") || "управление недоступно"}`:description}</small></span><i /></label>)}</div><div className="dnsOptionList"><label><span><strong>Резервный DNS</strong><small>использовать второй адрес</small></span><input type="checkbox" checked={dnsDraft?.fallback_enabled ?? true} onChange={(e) => setDnsDraft((v) => v ? {...v,fallback_enabled:e.target.checked}:v)} /></label><label><span><strong>DoH для VRX</strong><small>encrypted resolver для Xray</small></span><input type="checkbox" checked={dnsDraft?.prefer_encrypted ?? false} onChange={(e) => setDnsDraft((v) => v ? {...v,prefer_encrypted:e.target.checked}:v)} /></label></div></aside>
    </div>
    <div className="dnsLowerGrid"><article className="dnsCustomPanel"><header><div><p className="eyebrow">CUSTOM RESOLVER</p><h3>Собственный DNS</h3></div><button type="button" className={dnsDraft?.selected_id === "custom" ? "active":""} onClick={() => setDnsDraft((v) => v ? {...v,selected_id:"custom",custom:v.custom || {name:"Собственный DNS",addresses:[""],doh_url:""}}:v)}>Использовать</button></header>{dnsDraft?.selected_id === "custom" && <div><label><span>Название</span><input value={dnsDraft.custom?.name || ""} onChange={(e) => setDnsDraft((v) => v ? {...v,custom:{...(v.custom || {addresses:[""],doh_url:""}),name:e.target.value}}:v)} /></label><label><span>IP-адреса</span><input value={(dnsDraft.custom?.addresses || []).join(", ")} onChange={(e) => setDnsDraft((v) => v ? {...v,custom:{...(v.custom || {name:"DNS",doh_url:""}),addresses:e.target.value.split(",").map((x) => x.trim()).filter(Boolean)}}:v)} /></label><label><span>DoH URL</span><input value={dnsDraft.custom?.doh_url || ""} onChange={(e) => setDnsDraft((v) => v ? {...v,custom:{...(v.custom || {name:"DNS",addresses:[""]}),doh_url:e.target.value}}:v)} /></label></div>}</article><article className="dnsEffectivePanel"><header><p className="eyebrow">EFFECTIVE STATE</p><h3>Фактические значения</h3></header><div>{Object.entries(dns?.protocol_effect_details || {}).map(([protocol,effect]) => <span className={effect.matches_selected ? "matches":"differs"} key={protocol}><b>{protocol === "vless-reality-xhttp" ? "VRX":protocol === "shadowsocks" ? "SS":protocol.toUpperCase()}</b><code>{effect.value}</code><em>{effect.matches_selected ? "MATCH":"DIFF"}</em></span>)}</div></article></div>
    <footer className="dnsApplyDock"><div><p className="eyebrow">READY TO APPLY</p><strong>{selectedName}</strong><span>{dnsDraft?.apply_system ? "DNS самого VPS будет изменён с проверкой и откатом при ошибке.":"DNS самого VPS останется без изменений."}</span></div><button type="button" onClick={() => void saveDnsSettings()} disabled={busy || !dnsDraft}>{busy ? "Применяем…":"Применить политику"}</button></footer>
  </section>;
}
