"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DnsCheck, DnsSettings, DnsStatus } from "../../shared/types/control-plane";

type Props = { dns: DnsStatus | null; dnsDraft: DnsSettings | null; dnsChecks: Record<string, DnsCheck>; checkingDns: boolean; busy: boolean; setDnsDraft: Dispatch<SetStateAction<DnsSettings | null>>; checkDnsProviders: (providerId?: string) => Promise<void> | void; saveDnsSettings: () => Promise<void> | void; mihomoAvailable?: boolean; mihomoSelected?: boolean; onMihomoSelected?: (selected: boolean) => void };
const scopes = [["apply_wg", "WG", "WireGuard", "Только новые конфиги клиентов"], ["apply_awg", "AWG", "AmneziaWG", "Только новые конфиги клиентов"], ["apply_shadowsocks", "SS", "Shadowsocks", "Рекомендация клиенту"], ["apply_vrx", "VLESS", "Прямой VLESS", "Применяется сразу"]] as const;
const protocolByScope = { apply_wg: "wg", apply_awg: "awg", apply_shadowsocks: "shadowsocks", apply_vrx: "vless-reality-xhttp" } as const;

export function DnsView({ dns, dnsDraft, dnsChecks, checkingDns, busy, setDnsDraft, checkDnsProviders, saveDnsSettings, mihomoAvailable = false, mihomoSelected = false, onMihomoSelected }: Props) {
  const selected = dns?.providers.find((item) => item.id === dnsDraft?.selected_id);
  const selectedName = selected?.name || dnsDraft?.custom?.name || "DNS не выбран";
  const effects = Object.entries(dns?.protocol_effect_details || {}).filter(([, effect]) => effect.installed);
  const available = (key: typeof scopes[number][0]) => Boolean(dns?.protocol_effect_details?.[protocolByScope[key]]?.installed);
  const enabled = scopes.filter(([key]) => available(key) && Boolean(dnsDraft?.[key])).length;
  const effectLabel = (scope: string) => scope === "server_xray" ? "СРАЗУ" : scope === "new_profiles" ? "НОВЫЕ КОНФИГИ" : "РЕКОМЕНДАЦИЯ";
  const setSelected = (selected_id: string) => setDnsDraft((current) => current ? { ...current, selected_id } : current);

  return <section className="netDnsWorkspace dnsWorkspace" aria-label="SECURE CHANNELS · DNS">
    <div className="netDnsLayout">
      <article className="netDnsCatalog"><header className="netDnsBlockHead"><div><span className="netDnsKicker">RESOLVER CATALOG</span><h3>Доступные DNS</h3><p>Проверка выполняется с этого VPS.</p></div><button type="button" onClick={() => void checkDnsProviders()} disabled={checkingDns}>{checkingDns ? "Проверяем…" : "Проверить все"}</button></header><div className="netResolverList">{(dns?.providers || []).map((provider) => { const check = dnsChecks[provider.id]; const active = dnsDraft?.selected_id === provider.id; return <button type="button" className={`netResolverRow ${active ? "active" : ""}`} key={provider.id} onClick={() => setSelected(provider.id)}><span className="netResolverCountry">{provider.country}</span><span className="netResolverInfo"><strong>{provider.name}</strong><small>{provider.filter}</small><code>{provider.addresses.join("  ")}</code></span><span className="netResolverChecks"><b className={check?.udp_ok ? "ok" : ""}>UDP {check?.udp_ms != null ? `${check.udp_ms} ms` : "—"}</b><b className={check?.doh_ok ? "ok" : ""}>DoH {check?.doh_ms != null ? `${check.doh_ms} ms` : provider.doh_url ? "—" : "нет"}</b></span><em>{active ? "ВЫБРАН" : "ВЫБРАТЬ"}</em></button>; })}</div></article>

      <aside className="netDnsPolicy"><header className="netDnsBlockHead"><div><span className="netDnsKicker">APPLICATION SCOPE</span><h3>Куда применять</h3><p>Один выбор для установленных каналов.</p></div></header><div className="netScopeList">{scopes.map(([key, code, title, detail]) => { const isAvailable = available(key); return <label className={`${dnsDraft?.[key] && isAvailable ? "active" : ""} ${isAvailable ? "" : "disabled"}`} key={key}><input type="checkbox" disabled={!isAvailable} checked={isAvailable && (dnsDraft?.[key] ?? true)} onChange={(event) => setDnsDraft((current) => current ? { ...current, [key]: event.target.checked } : current)} /><b>{code}</b><span><strong>{title}</strong><small>{isAvailable ? detail : "Протокол не установлен"}</small></span></label>; })}{onMihomoSelected && <label className={`${mihomoSelected && mihomoAvailable ? "active" : ""} ${mihomoAvailable ? "" : "disabled"}`}><input type="checkbox" disabled={!mihomoAvailable} checked={mihomoAvailable && mihomoSelected} onChange={(event) => onMihomoSelected(event.target.checked)} /><b>MI</b><span><strong>Mihomo</strong><small>{mihomoAvailable ? "Настройки ядра ниже" : "Mihomo не установлен"}</small></span></label>}</div><div className="netDnsSwitches"><label><span><strong>Резервный DNS</strong><small>Использовать второй адрес</small></span><input type="checkbox" checked={dnsDraft?.fallback_enabled ?? true} onChange={(event) => setDnsDraft((current) => current ? { ...current, fallback_enabled: event.target.checked } : current)} /></label><label className={dns?.protocol_effect_details?.["vless-reality-xhttp"]?.installed ? "" : "disabled"}><span><strong>DoH для VLESS</strong><small>{dns?.protocol_effect_details?.["vless-reality-xhttp"]?.installed ? "Зашифрованный resolver для Xray" : "VLESS не установлен"}</small></span><input type="checkbox" disabled={!dns?.protocol_effect_details?.["vless-reality-xhttp"]?.installed} checked={dnsDraft?.prefer_encrypted ?? false} onChange={(event) => setDnsDraft((current) => current ? { ...current, prefer_encrypted: event.target.checked } : current)} /></label></div></aside>
    </div>

    <div className="netDnsSecondary"><article className="netExternalResolver"><header className="netDnsBlockHead"><div><span className="netDnsKicker">EXTERNAL RESOLVER</span><h3>Сторонний DNS</h3><p>Добавьте DNS, которого нет в каталоге.</p></div><button type="button" className={dnsDraft?.selected_id === "custom" ? "active" : ""} onClick={() => setDnsDraft((current) => current ? { ...current, selected_id: "custom", custom: current.custom || { name: "Сторонний DNS", addresses: [""], doh_url: "" } } : current)}>{dnsDraft?.selected_id === "custom" ? "Выбран" : "Добавить"}</button></header>{dnsDraft?.selected_id === "custom" && <div className="netExternalFields"><label><span>Название</span><input value={dnsDraft.custom?.name || ""} onChange={(event) => setDnsDraft((current) => current ? { ...current, custom: { ...(current.custom || { addresses: [""], doh_url: "" }), name: event.target.value } } : current)} /></label><label><span>IP-адреса</span><input placeholder="1.1.1.1, 1.0.0.1" value={(dnsDraft.custom?.addresses || []).join(", ")} onChange={(event) => setDnsDraft((current) => current ? { ...current, custom: { ...(current.custom || { name: "DNS", doh_url: "" }), addresses: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) } } : current)} /></label><label><span>DoH URL</span><input placeholder="https://…/dns-query" value={dnsDraft.custom?.doh_url || ""} onChange={(event) => setDnsDraft((current) => current ? { ...current, custom: { ...(current.custom || { name: "DNS", addresses: [""] }), doh_url: event.target.value } } : current)} /></label></div>}</article><article className="netEffective"><header className="netDnsBlockHead"><div><span className="netDnsKicker">EFFECTIVE STATE</span><h3>Фактическое применение</h3><p>Что уже видят установленные протоколы.</p></div><span className="netEffectiveCount">{effects.length ? `${effects.length} протокола` : "Нет установленных протоколов"}</span></header><div className="netEffectiveRows">{effects.length ? effects.map(([protocol, effect]) => <div className={effect.matches_selected ? "matches" : "differs"} key={protocol}><b>{protocol === "vless-reality-xhttp" ? "VLESS" : protocol === "shadowsocks" ? "SS" : protocol.toUpperCase()}</b><code>{effect.value}</code><small>{effectLabel(effect.scope)} · {effect.matches_selected ? "СОВПАДАЕТ" : "ОТЛИЧАЕТСЯ"}</small></div>) : <p>После установки протокола появится его фактический DNS.</p>}</div></article></div>

    <aside className="netDnsImpact"><strong>После применения</strong><span><b>VLESS</b> Xray получит выбранные resolver-ы и перезапустится.</span><span><b>WG/AWG</b> — только новые конфиги клиентов.</span><span><b>SS</b> — рекомендация для клиента; серверный трафик не изменяется.</span></aside>
    <footer className="netDnsApply dnsApplyDock"><div><span className="netDnsKicker">READY TO APPLY</span><strong>{selectedName}</strong><small>Изменения применяются только к отмеченным каналам.</small></div><button type="button" onClick={() => void saveDnsSettings()} disabled={busy || !dnsDraft}>{busy ? "Применяем…" : "Применить политику"}</button></footer>
  </section>;
}
