"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DnsCheck, DnsSettings, DnsStatus } from "../../shared/types/control-plane";
import { SystemDnsControl } from "./system-dns-control";

type Props = { dns: DnsStatus | null; dnsDraft: DnsSettings | null; dnsChecks: Record<string, DnsCheck>; checkingDns: boolean; busy: boolean; loading: boolean; dirty: boolean; setDnsDraft: Dispatch<SetStateAction<DnsSettings | null>>; checkDnsProviders: () => Promise<void>; saveDnsSettings: () => Promise<void> };

function Probe({ label, ok, ms, checked, supported = true }: { label: string; ok?: boolean; ms?: number; checked: boolean; supported?: boolean }) {
  return <span className={checked && supported ? ok ? "networkProbeOk" : "networkProbeFail" : ""}>{label}<b>{!supported ? "Нет" : !checked ? "Не проверен" : !ok ? "Ошибка" : ms != null ? `${ms} мс` : "Доступен"}</b></span>;
}

export function DnsView({ dns, dnsDraft, dnsChecks, checkingDns, busy, loading, dirty, setDnsDraft, checkDnsProviders, saveDnsSettings }: Props) {
  if (!dns || !dnsDraft) return <div className="networkEmpty"><h2>Настройки DNS недоступны</h2><p>Обновите состояние сети, чтобы загрузить настройки.</p></div>;
  const selected = dnsDraft.profiles?.system || dnsDraft.selected_id;
  const selectedName = selected === "custom" ? dnsDraft.custom?.name || "Сторонний DNS" : dns.providers.find((provider) => provider.id === selected)?.name || "DNS не выбран";
  const customUsed = selected === "custom" || Object.values(dnsDraft.profiles || {}).includes("custom");
  const effects = Object.entries(dns.protocol_effect_details || {}).filter(([, effect]) => effect.installed);
  const updateCustom = (patch: Partial<NonNullable<DnsSettings["custom"]>>) => setDnsDraft((current) => current ? { ...current, custom: { name: "Сторонний DNS", addresses: [], doh_url: "", ...current.custom, ...patch } } : current);
  const choose = (id: string) => setDnsDraft((current) => current ? { ...current, selected_id: id, profiles: { ...(current.profiles || {}), system: id } } : current);
  const customValid = !customUsed || Boolean(dnsDraft.custom?.addresses.length && dnsDraft.custom.addresses.every((address) => address.trim()));
  return <form className="networkDnsForm" onSubmit={(event) => { event.preventDefault(); if (dirty && customValid) void saveDnsSettings(); }}>
    <fieldset disabled={busy} className="networkDnsFields">
      <div className="networkDnsWorkbench">
        <article className="networkPanel networkResolverBrowser"><div className="networkResolverArt" aria-hidden="true" /><div className="networkSectionHeading"><div><span className="networkCaption">Каталог DNS</span><h2>Доступные DNS</h2><p>Адреса, назначение и результат проверки с этого VPS.</p></div><button type="button" disabled={checkingDns || loading} onClick={() => void checkDnsProviders()}>{checkingDns ? "Проверяем…" : "Проверить все"}</button></div>
          <div className="networkResolverList">{dns.providers.filter((provider) => provider.id !== "custom").map((provider) => { const check = dnsChecks[provider.id]; const active = selected === provider.id; return <button type="button" className={`networkResolverRow ${active ? "selected" : ""}`} key={provider.id} aria-pressed={active} onClick={() => choose(provider.id)}><span className="networkResolverCountry">{provider.country}</span><span className="networkResolverIdentity"><strong>{provider.name}</strong><small>{provider.filter || "Без описания фильтрации"}</small><code>{provider.addresses.join(" · ")}</code></span><span className="networkProbeResults"><Probe label="UDP" checked={Boolean(check)} ok={check?.udp_ok} ms={check?.udp_ms} /><Probe label="DoH" checked={Boolean(check)} supported={Boolean(provider.doh_url)} ok={check?.doh_ok} ms={check?.doh_ms} /></span><em>{active ? "Выбран" : "Выбрать"}</em></button>; })}</div>
          {!dns.providers.length && <p className="networkPanelNote">Каталог провайдеров пуст. Можно указать сторонний DNS.</p>}
          <p className="networkCatalogHint">Выбранный DNS задаёт профиль VPS. Профили отдельных компонентов можно изменить справа.</p>
        </article>
        <aside className="networkDnsPolicy"><SystemDnsControl dns={dns} dnsDraft={dnsDraft} setDnsDraft={setDnsDraft} /><div className="networkDnsOptions"><label><span><strong>Резервный DNS</strong><small>Использовать второй адрес провайдера.</small></span><input type="checkbox" checked={dnsDraft.fallback_enabled} onChange={(event) => { const checked = event.target.checked; setDnsDraft((current) => current ? { ...current, fallback_enabled: checked } : current); }} /></label><label><span><strong>DoH для VLESS</strong><small>{dns.protocol_effect_details?.["vless-reality-xhttp"]?.installed ? "Зашифрованный DNS для VLESS, если он есть в профиле." : "Доступно после установки прямого VLESS."}</small></span><input type="checkbox" disabled={!dns.protocol_effect_details?.["vless-reality-xhttp"]?.installed} checked={dnsDraft.prefer_encrypted} onChange={(event) => { const checked = event.target.checked; setDnsDraft((current) => current ? { ...current, prefer_encrypted: checked } : current); }} /></label></div></aside>
      </div>
      <div className="networkDnsLowerGrid">
        <article className="networkPanel networkCustom"><div className="networkCustomHeading"><div><span className="networkCaption">Свой провайдер</span><h3>Сторонний DNS</h3><p>Добавьте DNS, которого нет в каталоге.</p></div><button type="button" aria-pressed={selected === "custom"} onClick={() => choose("custom")}>{selected === "custom" ? "Выбран для VPS" : "Добавить DNS"}</button></div>{customUsed && <div className="networkCustomFields"><label>Название<input value={dnsDraft.custom?.name || ""} placeholder="Мой DNS" onChange={(event) => updateCustom({ name: event.target.value })} /></label><label>IP-адреса через запятую<input required value={dnsDraft.custom?.addresses.join(",") || ""} placeholder="1.1.1.1,1.0.0.1" onChange={(event) => updateCustom({ addresses: event.target.value.split(",") })} /></label><label>DoH URL <span>необязательно</span><input type="url" value={dnsDraft.custom?.doh_url || ""} placeholder="https://dns.example/dns-query" onChange={(event) => updateCustom({ doh_url: event.target.value })} /></label></div>}{!customValid && <p className="networkValidation">Для стороннего профиля укажите IP-адреса без пустых значений.</p>}</article>
        <article className="networkPanel networkEffective"><div className="networkSectionHeading"><div><span className="networkCaption">Фактическое применение</span><h3>DNS прямых подключений</h3><p>Текущее состояние установленных протоколов.</p></div></div><div className="networkEffectiveRows">{effects.length ? effects.map(([protocol, effect]) => <div key={protocol} className={effect.matches_selected ? "matches" : "differs"}><strong>{protocol === "vless-reality-xhttp" ? "VLESS" : protocol === "shadowsocks" ? "SS" : protocol.toUpperCase()}</strong><code>{effect.value || "Нет данных"}</code><small>{effect.scope === "server_xray" ? "Сразу в Xray" : effect.scope === "new_profiles" ? "Новые конфиги" : "Рекомендация"} · {effect.matches_selected ? "Совпадает" : "Отличается"}</small></div>) : <p>После установки протокола здесь появится его фактический DNS.</p>}</div></article>
      </div>
    </fieldset>
    <aside className="networkImpact"><strong>Что изменится после применения</strong><p>VPS получит системный DNS, если отмечен. VLESS перезапустит Xray. WireGuard и AmneziaWG используют DNS только в новых конфигурациях. Для Shadowsocks меняется рекомендация клиентам. DNS Mihomo настраивается в его разделе.</p></aside>
    <footer className={`networkSaveBar ${dirty ? "dirty" : ""}`}><div role="status"><i className={`networkDot ${dirty ? "proxy_or_cdn" : "direct"}`} /><span><strong>{busy ? "Применяем настройки…" : selectedName}</strong><small>{dirty ? "Есть несохранённые изменения. " : "Настройки сохранены. "}Изменения применяются только к отмеченным компонентам.</small></span></div><div className="networkSaveActions"><button type="button" disabled={!dirty || busy || loading} onClick={() => setDnsDraft(dns.settings)}>Сбросить</button><button type="submit" className="networkPrimaryButton" disabled={!dirty || busy || loading || !customValid}>{busy ? "Применяем…" : "Применить политику"}</button></div></footer>
  </form>;
}
