"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DnsCheck, DnsSettings, DnsStatus } from "../../shared/types/control-plane";
import { SystemDnsControl } from "./system-dns-control";

type Props = { dns: DnsStatus | null; dnsDraft: DnsSettings | null; dnsChecks: Record<string, DnsCheck>; checkingDns: boolean; busy: boolean; loading: boolean; dirty: boolean; setDnsDraft: Dispatch<SetStateAction<DnsSettings | null>>; checkDnsProviders: () => Promise<void>; saveDnsSettings: () => Promise<void> };

export function DnsView({ dns, dnsDraft, dnsChecks, checkingDns, busy, loading, dirty, setDnsDraft, checkDnsProviders, saveDnsSettings }: Props) {
  if (!dns || !dnsDraft) return <p className="networkEmpty">Настройки DNS недоступны. Обновите страницу.</p>;
  const selected = dnsDraft.profiles?.system || dnsDraft.selected_id;
  const reserve = !dnsDraft.fallback_enabled ? "off" : dnsDraft.fallback_id || "auto";
  const providers = dns.providers.filter((provider) => provider.id !== "custom");
  const customUsed = selected === "custom" || Object.values(dnsDraft.profiles || {}).includes("custom") || (dnsDraft.fallback_enabled && dnsDraft.fallback_id === "custom");
  const customValid = !customUsed || Boolean(dnsDraft.custom?.addresses.length && dnsDraft.custom.addresses.every((address) => address.trim()));
  const update = (patch: Partial<DnsSettings>) => setDnsDraft((current) => current ? { ...current, ...patch } : current);
  const choose = (id: string) => setDnsDraft((current) => current ? { ...current, selected_id: id, profiles: { ...(current.profiles || {}), system: id } } : current);
  const updateCustom = (patch: Partial<NonNullable<DnsSettings["custom"]>>) => setDnsDraft((current) => current ? { ...current, custom: { name: "Сторонний DNS", addresses: [], doh_url: "", ...current.custom, ...patch } } : current);
  const options = <>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}<option value="custom">{dnsDraft.custom?.name || "Сторонний DNS"}</option></>;
  const primary = dns.providers.find((provider) => provider.id === selected);
  const backup = dns.providers.find((provider) => provider.id === dnsDraft.fallback_id);
  const probeLabel = (check: DnsCheck | undefined, transport: "udp" | "doh") => !check ? "Не проверен" : !check[`${transport}_ok`] ? "Ошибка" : check[`${transport}_ms`] != null ? `${check[`${transport}_ms`]} мс` : "Доступен";
  return <form className="networkDnsForm" onSubmit={(event) => { event.preventDefault(); if (dirty && customValid) void saveDnsSettings(); }}>
    <fieldset disabled={busy} className="networkDnsFields">
      <section className="networkDnsSetup" aria-label="Основной и резервный DNS"><label><span className="networkFieldNumber">01</span><span className="networkFieldTitle">Основной DNS</span><select value={selected} onChange={(event) => choose(event.target.value)}>{options}</select><small>{primary?.addresses.join(" · ") || "Укажите адреса ниже"}</small></label><label><span className="networkFieldNumber">02</span><span className="networkFieldTitle">Резервный DNS</span><select value={reserve} onChange={(event) => update({ fallback_enabled: event.target.value !== "off", fallback_id: ["off", "auto"].includes(event.target.value) ? null : event.target.value })}><option value="off">Не использовать</option><option value="auto">Второй адрес основного провайдера</option>{options}</select><small>{reserve === "off" ? "Только основной адрес" : reserve === "auto" ? "Для каждого компонента из его профиля" : backup?.addresses[0] || "Укажите адреса ниже"}</small></label><div className="networkDnsPolicy"><span className="networkFieldNumber">03</span><span className="networkFieldTitle">Защита запросов</span><label className="networkSwitch"><input type="checkbox" disabled={!dns.protocol_effect_details?.["vless-reality-xhttp"]?.installed} checked={dnsDraft.prefer_encrypted} onChange={(event) => update({ prefer_encrypted: event.target.checked })} /><span>DoH для VLESS</span></label><small>Зашифрованный DNS для VLESS, если он есть у основного провайдера.</small></div></section>
      {customUsed && <section className="networkPanel networkCustom"><header className="networkSectionHeading"><div><h2>Сторонний DNS</h2><p>Этот профиль доступен как основной и как резервный.</p></div></header><div className="networkCustomFields"><label>Название<input value={dnsDraft.custom?.name || ""} placeholder="Мой DNS" onChange={(event) => updateCustom({ name: event.target.value })} /></label><label>IP-адреса через запятую<input required value={dnsDraft.custom?.addresses.join(",") || ""} placeholder="1.1.1.1,1.0.0.1" onChange={(event) => updateCustom({ addresses: event.target.value.split(",") })} /></label><label>DoH URL, необязательно<input type="url" value={dnsDraft.custom?.doh_url || ""} placeholder="https://dns.example/dns-query" onChange={(event) => updateCustom({ doh_url: event.target.value })} /></label></div>{!customValid && <p className="networkValidation">Укажите IP-адреса без пустых значений.</p>}</section>}
      <SystemDnsControl dns={dns} dnsDraft={dnsDraft} setDnsDraft={setDnsDraft} />
      <details className="networkCatalog"><summary><span>Доступные DNS</span><small>{providers.length} провайдеров · адреса и проверка доступности</small></summary><div className="networkCatalogToolbar"><p>Проверка выполняется с VPS.</p><button type="button" disabled={checkingDns || loading} onClick={() => void checkDnsProviders()}>{checkingDns ? "Проверяем…" : "Проверить все"}</button></div><div className="networkTableWrap"><table><thead><tr><th>Провайдер</th><th>Адреса</th><th>Фильтрация</th><th>UDP</th><th>DoH</th></tr></thead><tbody>{providers.map((provider) => <tr key={provider.id}><td><strong>{provider.name}</strong><small>{provider.country}</small></td><td><code>{provider.addresses.join(", ")}</code></td><td>{provider.filter}</td><td>{probeLabel(dnsChecks[provider.id], "udp")}</td><td>{provider.doh_url ? probeLabel(dnsChecks[provider.id], "doh") : "Нет"}</td></tr>)}</tbody></table></div></details>
    </fieldset>
    <p className="networkImpact">VLESS перезапустит Xray. WG/AWG получат DNS в новых конфигурациях; существующие не меняются. Резерв добавляется к основному адресу, порядок запросов зависит от компонента. Настройки Mihomo находятся в его разделе.</p>
    <footer className={`networkSaveBar ${dirty ? "dirty" : ""}`}><div role="status"><strong>{busy ? "Применяем…" : dirty ? "Есть несохранённые изменения" : "Настройки сохранены"}</strong><small>Изменения применяются только к отмеченным компонентам.</small></div><div className="networkSaveActions"><button type="button" disabled={!dirty || busy || loading} onClick={() => setDnsDraft(dns.settings)}>Сбросить</button><button type="submit" className="networkPrimaryButton" disabled={!dirty || busy || loading || !customValid}>{busy ? "Применяем…" : "Применить настройки"}</button></div></footer>
  </form>;
}
