"use client";

import type { Dispatch, SetStateAction } from "react";
import type { DnsCheck, DnsSettings, DnsStatus } from "../../shared/types/control-plane";
import { SystemDnsControl } from "./system-dns-control";

type Props = { dns: DnsStatus | null; dnsDraft: DnsSettings | null; dnsChecks: Record<string, DnsCheck>; checkingDns: boolean; busy: boolean; loading: boolean; dirty: boolean; setDnsDraft: Dispatch<SetStateAction<DnsSettings | null>>; checkDnsProviders: () => Promise<void>; saveDnsSettings: () => Promise<void> };

function Probe({ label, ok, ms, checked, supported = true }: { label: string; ok?: boolean; ms?: number; checked: boolean; supported?: boolean }) {
  return <span className={checked && supported ? ok ? "networkProbeOk" : "networkProbeFail" : ""}>{label}<b>{!supported ? "Нет" : !checked ? "Не проверен" : !ok ? "Ошибка" : ms != null ? `${ms} мс` : "Доступен"}</b></span>;
}

export function DnsView({ dns, dnsDraft, dnsChecks, checkingDns, busy, loading, dirty, setDnsDraft, checkDnsProviders, saveDnsSettings }: Props) {
  if (!dns || !dnsDraft) return <div className="networkEmpty"><h2>Настройки DNS недоступны</h2><p>Обновите состояние сети, чтобы загрузить настройки.</p></div>;
  const selected = dnsDraft.profiles?.system || dnsDraft.selected_id;
  const customUsed = selected === "custom" || Object.values(dnsDraft.profiles || {}).includes("custom");
  const updateCustom = (patch: Partial<NonNullable<DnsSettings["custom"]>>) => setDnsDraft((current) => current ? { ...current, custom: { name: "Сторонний DNS", addresses: [], doh_url: "", ...current.custom, ...patch } } : current);
  const choose = (id: string) => setDnsDraft((current) => current ? { ...current, selected_id: id, profiles: { ...(current.profiles || {}), system: id } } : current);
  const customValid = !customUsed || Boolean(dnsDraft.custom?.addresses.length && dnsDraft.custom.addresses.every((address) => address.trim()));
  return <form className="networkDnsForm" onSubmit={(event) => { event.preventDefault(); if (dirty && customValid) void saveDnsSettings(); }}>
    <fieldset disabled={busy} className="networkDnsFields">
      <section className="networkPanel"><div className="networkSectionHeading"><div><span className="networkCaption">01 / Профиль сервера</span><h2>Выберите DNS-провайдера</h2><p>Карточка задаёт профиль VPS. Для протоколов можно выбрать отдельные профили ниже.</p></div><button type="button" disabled={checkingDns || loading} onClick={() => void checkDnsProviders()}>{checkingDns ? "Проверяем доступность…" : "Проверить с VPS"}</button></div>
        <div className="networkProviderGrid">{dns.providers.filter((provider) => provider.id !== "custom").map((provider) => { const check = dnsChecks[provider.id]; return <button type="button" className={`networkProvider ${selected === provider.id ? "selected" : ""}`} key={provider.id} aria-pressed={selected === provider.id} onClick={() => choose(provider.id)}><span className="networkProviderHeading"><span className="networkProviderCountry">{provider.country}</span><strong>{provider.name}</strong><span className="networkRadio" aria-hidden="true" /></span><span className="networkProviderFilter">{provider.filter || "Без описания фильтрации"}</span><code>{provider.addresses.join(" · ")}</code><span className="networkProbeResults"><Probe label="UDP" checked={Boolean(check)} ok={check?.udp_ok} ms={check?.udp_ms} /><Probe label="DoH" checked={Boolean(check)} supported={Boolean(provider.doh_url)} ok={check?.doh_ok} ms={check?.doh_ms} /></span></button>; })}</div>
        {!dns.providers.length && <p className="networkPanelNote">Каталог провайдеров пуст. Можно указать сторонний DNS.</p>}
        <div className="networkCustom"><div className="networkCustomHeading"><div><h3>Сторонний DNS</h3><p>Собственные IP-адреса и необязательный адрес DNS-over-HTTPS.</p></div><button type="button" aria-pressed={selected === "custom"} onClick={() => choose("custom")}>{selected === "custom" ? "Выбран для VPS" : "Выбрать для VPS"}</button></div><div className="networkCustomFields"><label>Название<input value={dnsDraft.custom?.name || ""} placeholder="Мой DNS" onChange={(event) => updateCustom({ name: event.target.value })} /></label><label>IP-адреса через запятую<input required={customUsed} value={dnsDraft.custom?.addresses.join(",") || ""} placeholder="1.1.1.1,1.0.0.1" onChange={(event) => updateCustom({ addresses: event.target.value.split(",") })} /></label><label>DoH URL <span>необязательно</span><input type="url" value={dnsDraft.custom?.doh_url || ""} placeholder="https://dns.example/dns-query" onChange={(event) => updateCustom({ doh_url: event.target.value })} /></label></div>{!customValid && <p className="networkValidation">Для стороннего профиля укажите IP-адреса без пустых значений.</p>}</div>
      </section>
      <SystemDnsControl dns={dns} dnsDraft={dnsDraft} setDnsDraft={setDnsDraft} />
      <section className="networkPanel"><div className="networkSectionHeading"><div><span className="networkCaption">03 / Поведение DNS</span><h2>Дополнительные параметры</h2></div></div><div className="networkDnsOptions"><label><span><strong>Резервный DNS</strong><small>Использовать второй адрес выбранного провайдера.</small></span><input type="checkbox" checked={dnsDraft.fallback_enabled} onChange={(event) => { const checked = event.target.checked; setDnsDraft((current) => current ? { ...current, fallback_enabled: checked } : current); }} /></label><label><span><strong>Зашифрованный DNS для VLESS</strong><small>{dns.protocol_effect_details?.["vless-reality-xhttp"]?.installed ? "Использовать DoH в Xray, если он есть в профиле." : "Доступно после установки прямого VLESS."}</small></span><input type="checkbox" disabled={!dns.protocol_effect_details?.["vless-reality-xhttp"]?.installed} checked={dnsDraft.prefer_encrypted} onChange={(event) => { const checked = event.target.checked; setDnsDraft((current) => current ? { ...current, prefer_encrypted: checked } : current); }} /></label></div></section>
    </fieldset>
    <aside className="networkImpact"><strong>Что изменится после применения</strong><p>VPS получит системный DNS, если отмечен. VLESS перезапустит Xray. WireGuard и AmneziaWG используют DNS только в новых конфигурациях. Для Shadowsocks меняется рекомендация клиентам. DNS Mihomo настраивается в его разделе.</p></aside>
    <footer className={`networkSaveBar ${dirty ? "dirty" : ""}`}><div role="status"><i className={`networkDot ${dirty ? "proxy_or_cdn" : "direct"}`} /><span><strong>{busy ? "Применяем настройки…" : dirty ? "Есть несохранённые изменения" : "Настройки сохранены"}</strong><small>Изменения применяются только к отмеченным компонентам.</small></span></div><div className="networkSaveActions"><button type="button" disabled={!dirty || busy || loading} onClick={() => setDnsDraft(dns.settings)}>Сбросить</button><button type="submit" className="networkPrimaryButton" disabled={!dirty || busy || loading || !customValid}>{busy ? "Применяем…" : "Применить DNS"}</button></div></footer>
  </form>;
}
