# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x06\x64\x61\x65mon\"/\n\x1bSubscribeConnectionsRequest\x12\x10\n\x08interval\x18\x01 \x01(\x03\"d\n\nConnection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\n \x01(\t\x12\x10\n\x08\x63losedAt\x18\r \x01(\x03\x12\x13\n\x0buplinkTotal\x18\x10 \x01(\x03\x12\x15\n\rdownlinkTotal\x18\x11 \x01(\x03\"\x91\x01\n\x0f\x43onnectionEvent\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12&\n\nconnection\x18\x03 \x01(\x0b\x32\x12.daemon.Connection\x12\x13\n\x0buplinkDelta\x18\x04 \x01(\x03\x12\x15\n\rdownlinkDelta\x18\x05 \x01(\x03\x12\x10\n\x08\x63losedAt\x18\x06 \x01(\x03\"J\n\x10\x43onnectionEvents\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.daemon.ConnectionEvent\x12\r\n\x05reset\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBECONNECTIONSREQUEST']._serialized_start=27
  _globals['_SUBSCRIBECONNECTIONSREQUEST']._serialized_end=74
  _globals['_CONNECTION']._serialized_start=76
  _globals['_CONNECTION']._serialized_end=176
  _globals['_CONNECTIONEVENT']._serialized_start=179
  _globals['_CONNECTIONEVENT']._serialized_end=324
  _globals['_CONNECTIONEVENTS']._serialized_start=326
  _globals['_CONNECTIONEVENTS']._serialized_end=400
# @@protoc_insertion_point(module_scope)
